In [ ]:
import pandas as pd
import joblib
import numpy as np

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [ ]:
df=pd.read_csv("/content/diabetes.csv")

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
df.shape

(768, 9)

In [ ]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:

def split_data(df):
    X = df.drop("Outcome", axis=1)
    y = df["Outcome"]

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )

    return X_train, X_test, y_train, y_test

In [ ]:
X_train, X_test, y_train, y_test = split_data(df)

In [ ]:
def train_model(model, X_train, y_train):
    model.fit(X_train, y_train)
    return model

In [ ]:
lr = LogisticRegression(max_iter=1000)
knn = KNeighborsClassifier(n_neighbors=5)
dt = DecisionTreeClassifier(random_state=42)

In [ ]:
lr = train_model(lr, X_train, y_train)
knn = train_model(knn, X_train, y_train)
dt = train_model(dt, X_train, y_train)

In [ ]:
def evaluate_model(model, X_test, y_test):

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    print("Accuracy :", accuracy)
    print("Precision:", precision)
    print("Recall   :", recall)
    print("F1 Score :", f1)
    print("Confusion Matrix:")
    print(cm)

    return accuracy, precision, recall, f1

In [ ]:
print("===== Logistic Regression =====")
lr_results = evaluate_model(lr, X_test, y_test)

===== Logistic Regression =====
Accuracy : 0.7467532467532467
Precision: 0.6379310344827587
Recall   : 0.6727272727272727
F1 Score : 0.6548672566371682
Confusion Matrix:
[[78 21]
 [18 37]]

In [ ]:
print("\n===== KNN =====")
knn_results = evaluate_model(knn, X_test, y_test)

===== KNN =====
Accuracy : 0.6623376623376623
Precision: 0.5245901639344263
Recall   : 0.5818181818181818
F1 Score : 0.5517241379310345
Confusion Matrix:
[[70 29]
 [23 32]]

In [ ]:
print("\n===== Decision Tree =====")
dt_results = evaluate_model(dt, X_test, y_test)

===== Decision Tree =====
Accuracy : 0.7467532467532467
Precision: 0.625
Recall   : 0.7272727272727273
F1 Score : 0.6722689075630253
Confusion Matrix:
[[75 24]
 [15 40]]

In [ ]:
results = pd.DataFrame({
    "Model": ["Logistic Regression", "KNN", "Decision Tree"],
    "Accuracy": [lr_results[0], knn_results[0], dt_results[0]],
    "Precision": [lr_results[1], knn_results[1], dt_results[1]],
    "Recall": [lr_results[2], knn_results[2], dt_results[2]],
    "F1 Score": [lr_results[3], knn_results[3], dt_results[3]]
})

results

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.746753   0.637931  0.672727  0.654867
1                  KNN  0.662338   0.524590  0.581818  0.551724
2        Decision Tree  0.746753   0.625000  0.727273  0.672269

In [ ]:
joblib.dump(lr, "diabetes_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [ ]:
model = joblib.load("diabetes_model.pkl")

print("Model loaded successfully!")

Model loaded successfully!

In [ ]:
preg = int(input("Enter Pregnancies: "))
glucose = float(input("Enter Glucose: "))
bp = float(input("Enter Blood Pressure: "))
skin = float(input("Enter Skin Thickness: "))
insulin = float(input("Enter Insulin: "))
bmi = float(input("Enter BMI: "))
dpf = float(input("Enter Diabetes Pedigree Function: "))
age = int(input("Enter Age: "))

Enter Pregnancies: 2
Enter Glucose: 140
Enter Blood Pressure: 60
Enter Skin Thickness: 32
Enter Insulin: 44
Enter BMI: 28
Enter Diabetes Pedigree Function: 4
Enter Age: 35

In [ ]:
sample = [[
    preg,
    glucose,
    bp,
    skin,
    insulin,
    bmi,
    dpf,
    age
]]

In [ ]:
prediction = model.predict(sample)

if prediction[0] == 1:
    print("\nPrediction: Patient is Diabetic")
else:
    print("\nPrediction: Patient is Not Diabetic")

Prediction: Patient is Diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(